name: DevOps CI/CD Pipeline
on: [push]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Unit Tests..."

  Building:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Docker Image..."

  Deployment:
    needs: Building
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Jenkins..."
